name: kazakh_learning_app
description: OYU - Kazakh learning mobile app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.2.2
  http_parser: ^4.0.2

  shared_preferences: ^2.2.3

  google_sign_in: ^6.2.2

  file_picker: ^8.1.2
  mime: ^1.0.5

  audioplayers: ^6.1.0
  record: ^5.1.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/